
[[constraint]]
  name = "github.com/moovweb/gokogiri"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/mat/getxpath"
  go-version = "go1.11"
  install = [ "./..." ]
